/**
 * Banco de questões ORIGINAL do curso «Princípios da Transformação Digital».
 *
 * Dois instrumentos distintos e separados:
 * - EXAME: 60 questões para uma prova de 20 (secção 10 do TdR: banco activo com
 *   o triplo das questões do exame).
 * - PRE_POS: 10 questões de pré-teste e pós-teste, para medir evolução. NÃO é
 *   instrumento certificador.
 *
 * Estado: todas entram INACTIVAS (rascunho) — não activam certificação oficial
 * enquanto a Ologa/ATDI não as validar.
 *
 * Os gabaritos vivem aqui, fora de src/, e são carregados para a base de dados.
 * Nunca entram no pacote do navegador.
 */

export type QuestaoSeed = {
  /** m1 | m2 | m3 — módulo do curso */
  m: "m1" | "m2" | "m3";
  /** em = escolha múltipla, vf = verdadeiro/falso, cor = correspondência, ord = ordenação */
  t: "em" | "vf" | "cor" | "ord";
  /** f = fácil, me = média, di = difícil */
  d: "f" | "me" | "di";
  e: string;
  opts?: string[];
  ind?: number;
  val?: boolean;
  pares?: { esquerda: string; direita: string }[];
  seq?: string[];
  exp: string;
  obj: string;
};

export const EXAME: QuestaoSeed[] = [
  // ---------- Módulo 1 (20) ----------
  { m: "m1", t: "em", d: "f", e: "Qual das situações seguintes é transformação digital e não apenas digitalização?", opts: ["Publicar o formulário em PDF no sítio da instituição", "Rever o processo e eliminar a deslocação de levantamento", "Comprar computadores novos para o balcão", "Digitar em computador os pedidos recebidos em papel"], ind: 1, exp: "Transformação digital altera o próprio processo à luz da necessidade do utente; as restantes opções mantêm o processo antigo.", obj: "Distinguir digitação, digitalização e transformação digital." },
  { m: "m1", t: "vf", d: "f", e: "Automatizar um processo mal desenhado resolve o problema do processo.", val: false, exp: "Automatizar um processo confuso produz confusão mais depressa e torna a correcção mais cara.", obj: "Distinguir digitação, digitalização e transformação digital." },
  { m: "m1", t: "em", d: "f", e: "Quais são as quatro camadas que a transformação digital toca ao mesmo tempo?", opts: ["Orçamento, pessoal, obras e equipamento", "Pessoas, processos, dados e tecnologia", "Software, hardware, rede e energia", "Lei, regulamento, despacho e circular"], ind: 1, exp: "Quando só a tecnologia muda, o resultado é um serviço em linha com as mesmas exigências de antes.", obj: "Identificar mudanças institucionais além da tecnologia." },
  { m: "m1", t: "cor", d: "me", e: "Associe cada tecnologia ao problema que procura resolver.", pares: [{ esquerda: "Computação em nuvem", direita: "Capacidade de cálculo e armazenamento sem infra-estrutura própria" }, { esquerda: "Inteligência artificial", direita: "Tratar casos repetitivos em grande número e encontrar padrões" }, { esquerda: "Internet das coisas", direita: "Recolher informação do mundo físico sem registo manual" }, { esquerda: "Cadeia de blocos", direita: "Garantir que um registo partilhado não é alterado sem rasto" }], exp: "Cada tecnologia responde a um problema diferente; nenhuma corrige, por si, um processo mal desenhado.", obj: "Nomear cinco tecnologias e o problema que cada uma resolve." },
  { m: "m1", t: "em", d: "f", e: "Que problema procura resolver o tratamento de grandes volumes de dados?", opts: ["Reduzir o preço dos computadores", "Decidir com base em evidência e não em impressão", "Substituir o pessoal do atendimento", "Aumentar a velocidade da ligação à internet"], ind: 1, exp: "O valor está em sustentar decisões com informação, não em acumular registos.", obj: "Nomear cinco tecnologias e o problema que cada uma resolve." },
  { m: "m1", t: "vf", d: "me", e: "Um serviço público pode escolher servir apenas quem tem acesso ao canal digital.", val: false, exp: "O serviço público é devido a toda a população; uma solução que só funciona para parte dela não é aceitável.", obj: "Explicar os constrangimentos próprios da administração pública." },
  { m: "m1", t: "em", d: "me", e: "Antes de reutilizar dados de outro organismo, qual é a primeira verificação?", opts: ["O formato do ficheiro", "A base legal e o responsável pela qualidade do dado", "A velocidade da ligação", "A marca do sistema informático"], ind: 1, exp: "A parte técnica costuma ser a mais simples; é o acordo institucional e legal que determina o prazo.", obj: "Relacionar política pública com decisão concreta de um serviço." },
  { m: "m1", t: "em", d: "me", e: "Qual destas é uma competência digital que a equipa de um serviço precisa de ter?", opts: ["Saber programar em pelo menos duas linguagens", "Saber o que fazer quando o serviço digital falha", "Saber montar uma rede local", "Saber desenhar páginas na internet"], ind: 1, exp: "Sem esta competência a instituição fica dependente de quem instalou o sistema.", obj: "Identificar competências digitais necessárias à equipa." },
  { m: "m1", t: "em", d: "f", e: "Valor público é o mesmo que poupança orçamental?", opts: ["Sim, são conceitos equivalentes", "Não: poupança é apenas uma das formas de valor", "Sim, desde que o serviço fique mais barato", "Não, porque o valor público não é mensurável"], ind: 1, exp: "Um serviço que poupa dinheiro e afasta metade dos utentes destruiu valor público.", obj: "Definir valor público e distingui-lo de poupança." },
  { m: "m1", t: "vf", d: "me", e: "Uma descida do número total de pedidos após a digitalização é sempre sinal de sucesso.", val: false, exp: "Pode significar que há pessoas a deixar de conseguir pedir, e não que a necessidade desapareceu.", obj: "Identificar impactos sociais de um projecto digital." },
  { m: "m1", t: "em", d: "me", e: "Qual é um impacto ambiental negativo da digitalização de um serviço?", opts: ["Redução do consumo de papel", "Menos deslocações dos utentes", "Resíduos de equipamento eléctrico e electrónico substituído", "Melhor planeamento de recursos"], ind: 2, exp: "O balanço ambiental depende das escolhas: equipamento durável e reaproveitado altera o resultado.", obj: "Nomear impactos ambientais positivos e negativos." },
  { m: "m1", t: "em", d: "di", e: "Um sistema de apoio à decisão não permite explicar o critério usado nem contestar o resultado. Qual é o problema principal?", opts: ["É mais lento do que a decisão humana", "Impede a prestação de contas e o direito de reclamação", "Consome demasiada energia", "Exige formação adicional da equipa"], ind: 1, exp: "A possibilidade de justificar e rever a decisão é anterior a qualquer consideração técnica.", obj: "Identificar riscos éticos e jurídicos de um serviço." },
  { m: "m1", t: "em", d: "f", e: "Quantas dimensões propõe o diagnóstico de maturidade digital apresentado no curso?", opts: ["Três", "Quatro", "Cinco", "Sete"], ind: 2, exp: "Infra-estrutura, processos, dados, pessoas e governação.", obj: "Aplicar a grelha de maturidade digital." },
  { m: "m1", t: "cor", d: "me", e: "Associe cada nível de maturidade à sua descrição.", pares: [{ esquerda: "Inicial", direita: "Depende do esforço individual" }, { esquerda: "Em desenvolvimento", direita: "Há prática escrita mas não generalizada" }, { esquerda: "Estabelecido", direita: "É prática corrente e acompanhada" }, { esquerda: "Optimizado", direita: "É revisto com base em dados" }], exp: "Atribuir nível sem justificação escrita torna o diagnóstico inútil pouco tempo depois.", obj: "Aplicar a grelha de maturidade digital." },
  { m: "m1", t: "em", d: "me", e: "Uma instituição tem bons computadores e ligação estável, mas cada técnico trata o mesmo pedido à sua maneira. Qual é o passo seguinte mais rentável?", opts: ["Comprar mais equipamento", "Escrever o procedimento do pedido mais frequente", "Contratar mais pessoal", "Adquirir um sistema informático novo"], ind: 1, exp: "A dimensão mais atrasada é a dos processos; é aí que o investimento seguinte rende mais.", obj: "Produzir prioridades a partir de um diagnóstico." },
  { m: "m1", t: "em", d: "f", e: "Que três partes tem uma prioridade bem escrita?", opts: ["Custo, prazo e fornecedor", "O que muda, para quem, e como se saberá", "Objectivo, missão e visão", "Actividade, produto e relatório"], ind: 1, exp: "Sem estas três partes não é possível acompanhar a execução nem prestar contas.", obj: "Produzir prioridades a partir de um diagnóstico." },
  { m: "m1", t: "vf", d: "f", e: "O diagnóstico de maturidade serve para comparar instituições entre si e atribuir nota.", val: false, exp: "Serve para responder a uma pergunta prática: onde estamos hoje e qual é o passo seguinte realista.", obj: "Aplicar a grelha de maturidade digital." },
  { m: "m1", t: "ord", d: "di", e: "Ordene a sequência de trabalho recomendada neste curso.", seq: ["Perceber o serviço e quem o usa", "Simplificar o processo", "Escolher a tecnologia", "Medir o resultado para o utente"], exp: "Escolher a tecnologia antes de perceber o serviço é a causa mais comum de projectos que não melhoram nada.", obj: "Distinguir digitação, digitalização e transformação digital." },
  { m: "m1", t: "em", d: "di", e: "Uma direcção compara o investimento inicial de duas soluções e escolhe a mais barata. Que erro é provável ter cometido?", opts: ["Não ter consultado o fornecedor", "Não ter considerado o custo recorrente de operação e manutenção", "Não ter pedido três propostas", "Não ter avaliado a marca do equipamento"], ind: 1, exp: "O custo de manutenção é recorrente e determina se a solução sobrevive ao fim do financiamento.", obj: "Identificar impactos económicos de um projecto digital." },
  { m: "m1", t: "vf", d: "me", e: "Uma prática interna nunca escrita pode ser tratada como obrigação legal.", val: false, exp: "É frequente confundir hábito com norma; o fundamento de cada passo deve ser apurado ou assumido como desconhecido.", obj: "Explicar os constrangimentos próprios da administração pública." },

  // ---------- Módulo 2 (20) ----------
  { m: "m2", t: "em", d: "f", e: "Porque é que a observação complementa a conversa com utentes?", opts: ["Porque é mais rápida", "Porque as pessoas não se recordam de dificuldades que consideram banais", "Porque dispensa consentimento", "Porque produz números"], ind: 1, exp: "Hábito e vergonha explicam a maior parte das diferenças entre o que se diz e o que se faz.", obj: "Distinguir o que as pessoas dizem do que fazem." },
  { m: "m2", t: "em", d: "f", e: "O que torna um perfil de utente útil para desenhar um serviço?", opts: ["Idade, sexo e distrito", "Necessidade, contexto e barreira", "Profissão e rendimento", "Nome e número de processo"], ind: 1, exp: "Dados demográficos sozinhos não indicam o que é preciso mudar no serviço.", obj: "Descrever perfis de utentes com necessidades distintas." },
  { m: "m2", t: "vf", d: "f", e: "Uma barreira de acesso que não é registada tende a não ser resolvida.", val: true, exp: "O registo das barreiras é a condição mínima para que entrem nas decisões de desenho.", obj: "Descrever perfis de utentes incluindo barreiras de acesso." },
  { m: "m2", t: "em", d: "me", e: "Qual destas afirmações é informação e não impressão?", opts: ["Achamos que as pessoas preferem o canal digital", "De quinze pessoas ouvidas na segunda-feira, onze disseram que preferem o balcão", "Toda a gente hoje usa telemóvel", "Ninguém lê as instruções"], ind: 1, exp: "Informação tem origem identificada e limite reconhecido.", obj: "Recolher informação sobre quem usa o serviço." },
  { m: "m2", t: "em", d: "f", e: "Onde começa a jornada de um serviço público?", opts: ["No atendimento ao balcão", "Quando a pessoa percebe que precisa do serviço e procura informação", "Na entrada do pedido no sistema", "Na assinatura do responsável"], ind: 1, exp: "Grande parte da desistência acontece antes do primeiro contacto com a instituição.", obj: "Mapear a jornada de um serviço público." },
  { m: "m2", t: "em", d: "f", e: "Que quatro colunas compõem o mapa de jornada apresentado?", opts: ["Custo, prazo, risco e responsável", "O que a pessoa faz, com quem interage, quanto tempo demora, o que pode correr mal", "Entrada, processamento, saída e arquivo", "Canal, formulário, taxa e carimbo"], ind: 1, exp: "O mapa revela quase sempre que a maior parte do tempo do utente é passada à espera ou a deslocar-se.", obj: "Mapear a jornada de um serviço público." },
  { m: "m2", t: "em", d: "me", e: "Qual destas é uma melhoria de jornada que não exige software novo?", opts: ["Criar uma aplicação para telemóvel", "Deixar de exigir um documento que a instituição já possui", "Instalar quiosques electrónicos", "Migrar a base de dados para a nuvem"], ind: 1, exp: "Melhorias de instrução interna costumam ser as mais rápidas a produzir efeito na jornada.", obj: "Propor melhorias de baixo custo a partir do mapa." },
  { m: "m2", t: "vf", d: "me", e: "Um ponto de fricção é qualquer passo que consome tempo ou provoca desistência sem produzir valor.", val: true, exp: "Informação contraditória à entrada e documentos já detidos pela instituição são exemplos comuns.", obj: "Identificar pontos de fricção e o seu custo." },
  { m: "m2", t: "em", d: "f", e: "Qual é o primeiro critério de simplificação apresentado?", opts: ["Este passo produz decisão?", "Este passo é rápido?", "Este passo está informatizado?", "Este passo tem carimbo?"], ind: 0, exp: "Se ninguém decide nada com a informação recolhida, o passo é candidato a eliminação.", obj: "Aplicar critérios de simplificação a um procedimento." },
  { m: "m2", t: "ord", d: "me", e: "Ordene os três critérios de simplificação pela ordem apresentada no curso.", seq: ["Este passo produz decisão?", "A instituição já tem este dado?", "Este passo protege alguém de um risco real?"], exp: "A ordem importa: começa-se pela utilidade, depois pela duplicação, e só então pelo risco coberto.", obj: "Aplicar critérios de simplificação a um procedimento." },
  { m: "m2", t: "em", d: "me", e: "Qual é o limite legítimo da simplificação?", opts: ["A opinião do fornecedor", "Os controlos que cobrem um risco real e a prestação de contas", "O número de campos do formulário", "A disponibilidade orçamental"], ind: 1, exp: "O teste prático é conseguir escrever, numa linha, o risco que o passo mantido cobre.", obj: "Explicar por que razão simplificar antes de digitalizar reduz custo e risco." },
  { m: "m2", t: "vf", d: "me", e: "Digitalizar um processo confuso torna mais barato corrigi-lo depois.", val: false, exp: "Cada passo passa a ser ecrã, campo e regra; corrigir exige mudar sistema, formação e instruções.", obj: "Explicar por que razão simplificar antes de digitalizar reduz custo e risco." },
  { m: "m2", t: "em", d: "f", e: "O que define um dado pessoal?", opts: ["Estar num formulário oficial", "Permitir identificar uma pessoa, directamente ou por cruzamento", "Conter um número", "Ser recolhido ao balcão"], ind: 1, exp: "O critério não é o tipo de campo, é a possibilidade de identificação.", obj: "Distinguir dado pessoal de dado não pessoal." },
  { m: "m2", t: "cor", d: "me", e: "Associe cada princípio ou medida à sua descrição.", pares: [{ esquerda: "Recolha mínima", direita: "Pedir apenas o necessário à finalidade declarada" }, { esquerda: "Finalidade", direita: "Não usar para outro fim sem fundamento" }, { esquerda: "Controlo de acesso", direita: "Cada pessoa com a sua conta, sem palavras-passe partilhadas" }, { esquerda: "Cópia de segurança", direita: "Só conta se já tiver sido restaurada com êxito" }], exp: "São medidas ao alcance de qualquer direcção, mesmo sem equipa informática própria.", obj: "Aplicar os princípios de recolha mínima e finalidade." },
  { m: "m2", t: "em", d: "me", e: "Qual é a medida de segurança mais barata e mais frequentemente esquecida?", opts: ["Instalar antivírus pago", "Retirar o acesso a quem mudou de funções ou saiu", "Cifrar todo o disco", "Mudar de fornecedor de internet"], ind: 1, exp: "Contas activas de pessoas que já não trabalham no serviço são das falhas mais comuns.", obj: "Identificar medidas básicas de segurança." },
  { m: "m2", t: "em", d: "di", e: "Antes de contratar um serviço na nuvem, que três perguntas devem ficar escritas no contrato?", opts: ["Preço, prazo e desconto", "Onde ficam os dados, quem lhes acede do lado do fornecedor, como são devolvidos ou apagados", "Marca, versão e capacidade", "Horário de apoio, idioma e telefone"], ind: 1, exp: "Não são questões técnicas, são questões contratuais, e devem preceder a adesão.", obj: "Identificar medidas básicas de segurança." },
  { m: "m2", t: "vf", d: "f", e: "Enviar listas de dados pessoais por aplicações pessoais de mensagens é aceitável desde que seja urgente.", val: false, exp: "A maior parte das fugas em serviços pequenos resulta de conveniência e não de ataque técnico.", obj: "Identificar medidas básicas de segurança." },
  { m: "m2", t: "em", d: "di", e: "Um formulário tem vinte e dois campos e nove não têm utilizador conhecido. Qual é a acção correcta?", opts: ["Eliminar os nove de imediato", "Apurar o uso de cada um e eliminar apenas aqueles cujo uso se confirma inexistente", "Manter todos por precaução", "Informatizar os vinte e dois tal como estão"], ind: 1, exp: "Alguns campos podem ser exigência de relatório; a decisão deve ficar documentada campo a campo.", obj: "Eliminar ou fundir passos de um processo, justificando." },
  { m: "m2", t: "em", d: "di", e: "Numa recolha, treze de quinze pessoas afirmam preencher o formulário sozinhas, mas a observação mostra nove a pedir ajuda. Que conclusão é sustentada?", opts: ["As pessoas não dizem a verdade", "O formulário exige apoio na prática, ainda que as pessoas não o registem como dificuldade", "A amostra é insuficiente para qualquer conclusão", "A observação foi mal conduzida"], ind: 1, exp: "Pedir ajuda numa fila é banal e não fica na memória como dificuldade; o dado útil é o comportamento.", obj: "Distinguir o que as pessoas dizem do que fazem." },
  { m: "m2", t: "vf", d: "f", e: "Um guião de recolha deve usar perguntas abertas que não sugiram a resposta.", val: true, exp: "Perguntas fechadas disfarçadas de abertas devolvem a opinião de quem pergunta.", obj: "Recolher informação sobre quem usa o serviço." },

  // ---------- Módulo 3 (20) ----------
  { m: "m3", t: "em", d: "f", e: "O que é, na prática, definir uma estratégia?", opts: ["Listar todas as ideias possíveis", "Escolher o que não se vai fazer este ano", "Pedir mais orçamento", "Contratar uma consultoria"], ind: 1, exp: "A limitação raramente é de ideias; é de atenção da direcção e de pessoas disponíveis.", obj: "Traduzir um diagnóstico num plano com objectivos e prazos." },
  { m: "m3", t: "em", d: "f", e: "Quais são os dois critérios de priorização apresentados?", opts: ["Custo e prazo", "Valor para o utente e exequibilidade", "Visibilidade e urgência", "Risco e orçamento"], ind: 1, exp: "Cruzados, produzem uma ordem que se explica em duas frases perante terceiros.", obj: "Aplicar critérios de priorização a uma lista de iniciativas." },
  { m: "m3", t: "em", d: "f", e: "O que deve conter cada objectivo do plano de uma página?", opts: ["Resultado, responsável, prazo e indicador", "Missão, visão, valores e lema", "Fornecedor, preço, garantia e prazo", "Actividade, relatório e arquivo"], ind: 0, exp: "Planos extensos protegem quem os escreve e não ajudam quem os executa.", obj: "Traduzir um diagnóstico num plano com objectivos e prazos." },
  { m: "m3", t: "vf", d: "me", e: "As iniciativas não escolhidas devem ser apagadas da lista.", val: false, exp: "Devem ficar numa lista datada para reavaliação, evitando repetir a mesma discussão de três em três meses.", obj: "Aplicar critérios de priorização a uma lista de iniciativas." },
  { m: "m3", t: "em", d: "me", e: "Uma iniciativa depende de alteração de norma por outra entidade. Por onde se começa?", opts: ["Pela aquisição do sistema", "Pelo pedido formal com o prazo mais longo", "Pela formação da equipa", "Pela comunicação aos utentes"], ind: 1, exp: "A dependência não impede o arranque, mas determina a ordem de trabalho.", obj: "Identificar dependências e riscos de cada iniciativa." },
  { m: "m3", t: "em", d: "me", e: "Como se regista um risco de forma útil?", opts: ["Nomeando o culpado provável", "Indicando o que pode correr mal, o sinal de alerta e a resposta prevista", "Atribuindo-lhe uma percentagem", "Registando-o em acta"], ind: 1, exp: "Três riscos bem acompanhados valem mais do que uma matriz com trinta.", obj: "Identificar dependências e riscos de cada iniciativa." },
  { m: "m3", t: "em", d: "f", e: "Qual é a diferença entre responsável pelo serviço e responsável pelo sistema?", opts: ["Não há diferença prática", "O primeiro responde pelo resultado para o utente; o segundo pelo funcionamento técnico", "O primeiro é sempre externo", "O segundo decide as regras do serviço"], ind: 1, exp: "Sem responsável pelo serviço, as decisões de serviço passam a ser tomadas por critério técnico.", obj: "Explicar a diferença entre responsável pelo serviço e pelo sistema." },
  { m: "m3", t: "cor", d: "me", e: "Associe cada papel à sua função na matriz de responsabilidades.", pares: [{ esquerda: "Decide", direita: "Toma a decisão final e responde por ela" }, { esquerda: "Executa", direita: "Realiza o trabalho" }, { esquerda: "É consultado", direita: "Dá parecer antes da decisão" }, { esquerda: "É informado", direita: "Recebe o resultado depois da decisão" }], exp: "Escrever isto para cada decisão importante evita a paralisia de espera mútua.", obj: "Distribuir responsabilidades por papéis definidos." },
  { m: "m3", t: "em", d: "me", e: "Qual destas formas de cobrir uma lacuna de competências não envolve formação?", opts: ["Marcar um curso interno", "Simplificar o processo até a competência deixar de ser necessária", "Enviar a equipa a uma acção externa", "Produzir um manual"], ind: 1, exp: "É a opção mais barata e a mais esquecida; contratar apoio pontual e partilhar com outro organismo também são válidas.", obj: "Identificar lacunas de competências e formas de as cobrir." },
  { m: "m3", t: "em", d: "di", e: "Só uma pessoa sabe gerar o mapa mensal a partir do sistema. Qual é o conjunto mínimo de medidas?", opts: ["Aumentar o salário dessa pessoa", "Documentar o procedimento, formar uma segunda pessoa e guardar as credenciais na instituição", "Adquirir um sistema mais simples", "Deixar de produzir o mapa"], ind: 1, exp: "A dependência de uma só pessoa é risco de continuidade e resolve-se com decisão, não com investimento.", obj: "Identificar lacunas de competências e formas de as cobrir." },
  { m: "m3", t: "em", d: "f", e: "Qual é a primeira pergunta que as pessoas fazem perante uma mudança?", opts: ["Quanto custou o sistema", "O que muda no meu trabalho", "Quem decidiu isto", "Quando acaba o projecto"], ind: 1, exp: "Comunicação que começa pela estratégia perde a audiência antes de responder a esta pergunta.", obj: "Desenhar um plano de comunicação interna." },
  { m: "m3", t: "vf", d: "f", e: "A resistência à mudança deve ser tratada como informação e não como má vontade.", val: true, exp: "Tem quase sempre causas concretas: receio de perder competência, de perder controlo, e experiência anterior negativa.", obj: "Identificar causas de resistência à mudança." },
  { m: "m3", t: "em", d: "me", e: "Porque é que a formação prévia, sozinha, não garante a adopção?", opts: ["Porque é demasiado curta", "Porque a desistência acontece na primeira dificuldade real, se não houver apoio próximo", "Porque os manuais são longos", "Porque a equipa não quer aprender"], ind: 1, exp: "O apoio nas primeiras duas semanas tem mais efeito do que horas adicionais de sala.", obj: "Definir o apoio necessário nas primeiras semanas." },
  { m: "m3", t: "vf", d: "me", e: "Uma mudança que obriga os utentes ao canal novo sem alternativa é aceitável se o canal for mais eficiente.", val: false, exp: "Obrigar sem alternativa gera exclusão e desconfiança; tem de existir sempre um caminho garantido.", obj: "Definir o apoio necessário nas primeiras semanas." },
  { m: "m3", t: "em", d: "f", e: "«Número de pessoas formadas» é que tipo de indicador?", opts: ["De resultado", "De actividade", "De equidade", "De sustentabilidade"], ind: 1, exp: "O resultado seria, por exemplo, a proporção de pedidos concluídos à primeira depois da formação.", obj: "Distinguir indicador de actividade de indicador de resultado." },
  { m: "m3", t: "em", d: "f", e: "Que quatro elementos deve ter um indicador útil?", opts: ["Nome, meta, cor e gráfico", "O que mede, como se calcula, de onde vêm os dados, de quanto em quanto tempo é lido", "Responsável, prazo, custo e risco", "Título, fórmula, unidade e assinatura"], ind: 1, exp: "Sem fonte, o indicador morre no primeiro mês; sem periodicidade, ninguém o lê.", obj: "Definir indicadores de resultado com fonte e periodicidade." },
  { m: "m3", t: "em", d: "di", e: "O tempo médio de resposta baixou de doze para sete dias, mas os pedidos de balcão subiram para catorze. Que indicador permitiu ver isto?", opts: ["O indicador de actividade", "O indicador de equidade, que separa por canal ou por grupo", "O indicador financeiro", "O indicador de satisfação"], ind: 1, exp: "Uma média favorável pode esconder a deterioração de um canal ou de um grupo de utentes.", obj: "Definir indicadores de resultado, incluindo equidade." },
  { m: "m3", t: "em", d: "me", e: "Quais são as três dimensões práticas da sustentabilidade de uma solução?", opts: ["Legal, política e social", "Financeira, técnica e ambiental", "Humana, material e temporal", "Nacional, provincial e distrital"], ind: 1, exp: "Quem paga a manutenção, quem actualiza e corrige, e que destino tem o equipamento substituído.", obj: "Planear a revisão periódica e a sustentabilidade." },
  { m: "m3", t: "vf", d: "di", e: "Numa revisão periódica de um projecto, «parar» tem de ser uma das decisões possíveis.", val: true, exp: "Se a decisão de parar não existe, a revisão é apenas um relatório.", obj: "Planear a revisão periódica e a sustentabilidade." },
  { m: "m3", t: "ord", d: "di", e: "Ordene as etapas de implementação de uma iniciativa, conforme o módulo 3.", seq: ["Priorizar e escrever o plano de uma página", "Definir papéis e cobrir lacunas de competências", "Comunicar e apoiar a adopção nas primeiras semanas", "Medir resultados e rever periodicamente"], exp: "Medir antes de definir responsáveis produz indicadores sem dono.", obj: "Traduzir um diagnóstico num plano com objectivos e prazos." },
];

/** Pré-teste e pós-teste: 10 questões, instrumento NÃO certificador. */
export const PRE_POS: QuestaoSeed[] = [
  { m: "m1", t: "em", d: "f", e: "Transformação digital é, sobretudo:", opts: ["Comprar equipamento novo", "Mudar a forma como o serviço é concebido e prestado", "Criar uma página na internet", "Digitar documentos em computador"], ind: 1, exp: "A tecnologia é o meio; o fim é o serviço prestado às pessoas.", obj: "Conceito de transformação digital." },
  { m: "m1", t: "vf", d: "f", e: "Um serviço público pode funcionar apenas por canal digital.", val: false, exp: "Parte da população não lhe tem acesso e o serviço é devido a todos.", obj: "Constrangimentos do serviço público." },
  { m: "m1", t: "em", d: "f", e: "Valor público inclui:", opts: ["Apenas a poupança orçamental", "Tempo devolvido às pessoas e direitos exercidos", "Apenas o número de sistemas instalados", "Apenas a satisfação da direcção"], ind: 1, exp: "Poupança é uma das formas de valor, não a única.", obj: "Conceito de valor público." },
  { m: "m1", t: "vf", d: "f", e: "Digitalizar consome energia e produz resíduos electrónicos.", val: true, exp: "O balanço ambiental depende de escolhas de durabilidade e reaproveitamento.", obj: "Impactos ambientais." },
  { m: "m2", t: "em", d: "f", e: "Para conhecer quem usa o serviço deve-se:", opts: ["Perguntar à chefia", "Falar com utentes e observar o que fazem", "Consultar apenas o regulamento", "Estimar a partir da experiência"], ind: 1, exp: "As pessoas descrevem mal aquilo que fazem por hábito.", obj: "Conhecer os utentes." },
  { m: "m2", t: "vf", d: "f", e: "Deve simplificar-se o processo antes de o digitalizar.", val: true, exp: "Digitalizar cristaliza o processo e torna a correcção mais cara.", obj: "Simplificação antes da digitalização." },
  { m: "m2", t: "em", d: "f", e: "Dado pessoal é:", opts: ["Qualquer informação escrita", "Informação que permite identificar uma pessoa", "Apenas o nome completo", "Apenas o número do documento"], ind: 1, exp: "Inclui identificação por cruzamento com outra informação.", obj: "Protecção de dados." },
  { m: "m3", t: "em", d: "f", e: "Um plano útil deve indicar, para cada objectivo:", opts: ["Resultado, responsável, prazo e indicador", "Apenas o orçamento", "Apenas a actividade", "Apenas o prazo"], ind: 0, exp: "Sem estes quatro elementos não é possível acompanhar a execução.", obj: "Planeamento." },
  { m: "m3", t: "vf", d: "f", e: "O apoio nas primeiras semanas de utilização é decisivo para a adopção.", val: true, exp: "A desistência acontece na primeira dificuldade real sem ajuda.", obj: "Gestão da mudança." },
  { m: "m3", t: "em", d: "f", e: "«Número de sessões realizadas» é um indicador de:", opts: ["Resultado", "Actividade", "Equidade", "Impacto ambiental"], ind: 1, exp: "Indicadores de actividade contam o que a instituição fez, não o que mudou para o utente.", obj: "Indicadores." },
];
