-- FAQ inicial em RASCUNHO (publicada = false), baseada no funcionamento
-- actual da plataforma. Sem contactos, prazos de resposta nem regras por
-- definir. Gravada na base em 2026-09-30; a publicação é feita no painel
-- (Painel → FAQ e suporte) depois de revista.
INSERT INTO public.faq_perguntas (pergunta, resposta, categoria, ordem, publicada) VALUES
($q$Como crio a minha conta?$q$, $r$Abra «Entrar» e escolha criar conta. Indique o seu nome, email, palavra-passe, província e distrito (estes dois são obrigatórios). O tipo de deficiência é opcional e autodeclarado: serve apenas para adaptar a formação e pode alterá-lo ou apagá-lo quando quiser. Se o email já tiver conta, a plataforma avisa.$r$, 'Acesso', 10, false),
($q$Esqueci-me da palavra-passe. O que faço?$q$, $r$Na página «Entrar», escolha recuperar a palavra-passe e escreva o email da sua conta. Recebe uma mensagem com uma ligação para definir uma palavra-passe nova. Nunca envie a sua palavra-passe em pedidos de apoio.$r$, 'Acesso', 20, false),
($q$Preciso de conta para estudar?$q$, $r$Pode abrir os cursos e ler as lições sem conta. Sem sessão iniciada, o que marcar como feito fica guardado só no aparelho que está a usar e não conta para a sua formação. Os materiais anexados às lições (documentos, vídeos, legendas), o exame e o certificado exigem sessão.$r$, 'Acesso', 30, false),
($q$Que cursos existem?$q$, $r$A plataforma tem seis cursos: Princípios da Transformação Digital, Introdução à Inteligência Artificial, Computação em Nuvem, Segurança Cibernética Avançada, Redes Avançadas e Introdução à Segurança Cibernética, e Tecnologias Digitais do Governo. Em «Cursos» vê a carga horária, os módulos e as lições de cada um.$r$, 'Cursos', 40, false),
($q$Cada lição tem que formatos?$q$, $r$Todas as lições têm texto e podem ser ouvidas em voz alta pelo navegador. No topo de cada lição aparece o que já está disponível e o que ainda está por produzir; só é indicado como disponível o que existe de facto.$r$, 'Cursos', 50, false),
($q$Como me inscrevo numa turma?$q$, $r$As turmas são criadas e geridas pela coordenação da formação, por curso, província e local. Cada turma tem um código de oito caracteres. Para confirmar a sua inscrição ou o código da sua turma, fale com a coordenação da formação da sua instituição.$r$, 'Inscrição', 60, false),
($q$Como inscrevo a minha instituição?$q$, $r$Use o formulário «Inscrição de instituição». Pede os dados da instituição, o ponto focal e informação sobre colaboradores e condições de acesso, para planear a formação.$r$, 'Inscrição', 70, false),
($q$Onde fica guardado o meu progresso?$q$, $r$Se tiver sessão iniciada e estiver inscrito numa turma desse curso, cada lição marcada como feita fica guardada na sua conta e continua em qualquer aparelho. Caso contrário, fica apenas no aparelho. A página da lição diz sempre qual dos dois casos se aplica.$r$, 'Progresso', 80, false),
($q$Marcar uma lição como feita conta como presença?$q$, $r$Não. Marcar uma lição como feita não regista presença, não dá aprovação e não emite certificado. As presenças são registadas por sessão da turma.$r$, 'Progresso', 90, false),
($q$Como abro os documentos e vídeos de uma lição?$q$, $r$Com sessão iniciada, a secção «Materiais da lição» mostra, pela ordem definida, os materiais disponibilizados. Pode abrir num separador ou descarregar. Os vídeos tocam na própria página e, quando existem legendas, pode activá-las no leitor ou descarregá-las. Se uma ligação deixar de funcionar, recarregue a página: as ligações são temporárias.$r$, 'Materiais', 100, false),
($q$Porque não vejo materiais numa lição?$q$, $r$Só aparecem materiais que já foram disponibilizados para essa lição. Se a secção não aparece, a lição ainda não tem materiais disponíveis. Confirme também que tem sessão iniciada.$r$, 'Materiais', 110, false),
($q$Como funciona o exame final?$q$, $r$O exame final é feito online. É gerado no momento em que o inicia, com questões sorteadas do banco de questões do curso, por isso cada formando recebe uma prova diferente. As questões são de vários tipos: escolha múltipla, verdadeiro ou falso, associação de conceitos e casos práticos. O número de questões, a duração, as tentativas e o prazo são definidos por curso.$r$, 'Avaliação', 120, false),
($q$Quais são as condições para obter o certificado?$q$, $r$São duas condições cumulativas: assiduidade igual ou superior a 80% e nota final igual ou superior a 60%. As duas são mostradas sempre em separado, com o valor atingido e o limiar exigido. O certificado é individual, por formando e por curso.$r$, 'Certificados', 130, false),
($q$Como consulto a minha situação e obtenho o certificado?$q$, $r$Em «Certificados», escreva o seu código pessoal e escolha o curso. A plataforma mostra a nota final, a assiduidade e o prazo, e emite o certificado se as duas condições estiverem cumpridas.$r$, 'Certificados', 140, false),
($q$Como se confirma que um certificado é verdadeiro?$q$, $r$Cada certificado tem um código único de verificação. Em «Verificar certificado», qualquer pessoa pode escrever esse código e confirmar a autenticidade.$r$, 'Certificados', 150, false),
($q$Que opções de acessibilidade existem?$q$, $r$Na barra do topo pode aumentar ou reduzir o tamanho do texto (A+ e A−), activar o alto contraste, repor as opções e ajustar a velocidade da leitura em voz alta. Estes controlos funcionam com teclado e há uma ligação para saltar directamente para o conteúdo. As preferências ficam guardadas no seu aparelho.$r$, 'Acessibilidade', 160, false),
($q$A leitura em voz alta não funciona. Porquê?$q$, $r$A leitura usa as vozes instaladas no seu aparelho. Para manter a pronúncia correcta, só lê com uma voz de português de Portugal (pt-PT). Se o aparelho não a tiver, aparece um aviso: instale uma voz pt-PT nas definições do sistema e tente de novo.$r$, 'Acessibilidade', 170, false),
($q$Como peço apoio?$q$, $r$Em «Ajuda e suporte», com sessão iniciada, escolha o tema, escreva o assunto e a mensagem e envie. O estado do pedido (aberto, em tratamento ou resolvido) e a resposta aparecem nessa mesma página. Não escreva palavras-passe nem outros dados secretos na mensagem.$r$, 'Apoio', 180, false),
($q$Preciso de uma adaptação por causa de uma deficiência. Como a peço?$q$, $r$Envie um pedido de apoio com o tema «Acessibilidade» a descrever a adaptação de que precisa. Também pode indicar, no seu perfil, o tipo de deficiência (opcional), para que a formação possa ser adaptada.$r$, 'Apoio', 190, false);
