/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as OlogaRouteImport } from './routes/ologa'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OlogaIndexRouteImport } from './routes/ologa.index'
import { Route as OlogaNovaInstituicaoRouteImport } from './routes/ologa.nova-instituicao'
import { Route as OlogaInstituicoesIdRouteImport } from './routes/ologa.instituicoes.$id'

const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const OlogaRoute = OlogaRouteImport.update({
  id: '/ologa',
  path: '/ologa',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OlogaIndexRoute = OlogaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OlogaRoute,
} as any)
const OlogaNovaInstituicaoRoute = OlogaNovaInstituicaoRouteImport.update({
  id: '/nova-instituicao',
  path: '/nova-instituicao',
  getParentRoute: () => OlogaRoute,
} as any)
const OlogaInstituicoesIdRoute = OlogaInstituicoesIdRouteImport.update({
  id: '/instituicoes/$id',
  path: '/instituicoes/$id',
  getParentRoute: () => OlogaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/inscricao': typeof InscricaoRoute
  '/ologa': typeof OlogaRouteWithChildren
  '/verificar': typeof VerificarRoute
  '/ologa/nova-instituicao': typeof OlogaNovaInstituicaoRoute
  '/ologa/': typeof OlogaIndexRoute
  '/ologa/instituicoes/$id': typeof OlogaInstituicoesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/inscricao': typeof InscricaoRoute
  '/verificar': typeof VerificarRoute
  '/ologa/nova-instituicao': typeof OlogaNovaInstituicaoRoute
  '/ologa': typeof OlogaIndexRoute
  '/ologa/instituicoes/$id': typeof OlogaInstituicoesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/inscricao': typeof InscricaoRoute
  '/ologa': typeof OlogaRouteWithChildren
  '/verificar': typeof VerificarRoute
  '/ologa/nova-instituicao': typeof OlogaNovaInstituicaoRoute
  '/ologa/': typeof OlogaIndexRoute
  '/ologa/instituicoes/$id': typeof OlogaInstituicoesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/inscricao'
    | '/ologa'
    | '/verificar'
    | '/ologa/nova-instituicao'
    | '/ologa/'
    | '/ologa/instituicoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/inscricao'
    | '/verificar'
    | '/ologa/nova-instituicao'
    | '/ologa'
    | '/ologa/instituicoes/$id'
  id:
    | '__root__'
    | '/'
    | '/entrar'
    | '/inscricao'
    | '/ologa'
    | '/verificar'
    | '/ologa/nova-instituicao'
    | '/ologa/'
    | '/ologa/instituicoes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntrarRoute: typeof EntrarRoute
  InscricaoRoute: typeof InscricaoRoute
  OlogaRoute: typeof OlogaRouteWithChildren
  VerificarRoute: typeof VerificarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ologa': {
      id: '/ologa'
      path: '/ologa'
      fullPath: '/ologa'
      preLoaderRoute: typeof OlogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ologa/': {
      id: '/ologa/'
      path: '/'
      fullPath: '/ologa/'
      preLoaderRoute: typeof OlogaIndexRouteImport
      parentRoute: typeof OlogaRoute
    }
    '/ologa/nova-instituicao': {
      id: '/ologa/nova-instituicao'
      path: '/nova-instituicao'
      fullPath: '/ologa/nova-instituicao'
      preLoaderRoute: typeof OlogaNovaInstituicaoRouteImport
      parentRoute: typeof OlogaRoute
    }
    '/ologa/instituicoes/$id': {
      id: '/ologa/instituicoes/$id'
      path: '/instituicoes/$id'
      fullPath: '/ologa/instituicoes/$id'
      preLoaderRoute: typeof OlogaInstituicoesIdRouteImport
      parentRoute: typeof OlogaRoute
    }
  }
}

interface OlogaRouteChildren {
  OlogaNovaInstituicaoRoute: typeof OlogaNovaInstituicaoRoute
  OlogaIndexRoute: typeof OlogaIndexRoute
  OlogaInstituicoesIdRoute: typeof OlogaInstituicoesIdRoute
}

const OlogaRouteChildren: OlogaRouteChildren = {
  OlogaNovaInstituicaoRoute: OlogaNovaInstituicaoRoute,
  OlogaIndexRoute: OlogaIndexRoute,
  OlogaInstituicoesIdRoute: OlogaInstituicoesIdRoute,
}

const OlogaRouteWithChildren = OlogaRoute._addFileChildren(OlogaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntrarRoute: EntrarRoute,
  InscricaoRoute: InscricaoRoute,
  OlogaRoute: OlogaRouteWithChildren,
  VerificarRoute: VerificarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
