/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as RegistoRouteImport } from './routes/registo'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OlogaRouteImport } from './routes/ologa'
import { Route as InstituicaoRouteImport } from './routes/instituicao'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as FormacaoRouteImport } from './routes/formacao'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DefinirPalavraPasseRouteImport } from './routes/definir-palavra-passe'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAdminSetupRouteImport } from './routes/api/public/admin-setup'

const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OlogaRoute = OlogaRouteImport.update({
  id: '/ologa',
  path: '/ologa',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituicaoRoute = InstituicaoRouteImport.update({
  id: '/instituicao',
  path: '/instituicao',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const FormacaoRoute = FormacaoRouteImport.update({
  id: '/formacao',
  path: '/formacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirPalavraPasseRoute = DefinirPalavraPasseRouteImport.update({
  id: '/definir-palavra-passe',
  path: '/definir-palavra-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminSetupRoute = ApiPublicAdminSetupRouteImport.update({
  id: '/api/public/admin-setup',
  path: '/api/public/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/definir-palavra-passe': typeof DefinirPalavraPasseRoute
  '/entrar': typeof EntrarRoute
  '/formacao': typeof FormacaoRoute
  '/inscricao': typeof InscricaoRoute
  '/instituicao': typeof InstituicaoRoute
  '/ologa': typeof OlogaRoute
  '/perfil': typeof PerfilRoute
  '/recuperar': typeof RecuperarRoute
  '/registo': typeof RegistoRoute
  '/verificar': typeof VerificarRoute
  '/api/public/admin-setup': typeof ApiPublicAdminSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/definir-palavra-passe': typeof DefinirPalavraPasseRoute
  '/entrar': typeof EntrarRoute
  '/formacao': typeof FormacaoRoute
  '/inscricao': typeof InscricaoRoute
  '/instituicao': typeof InstituicaoRoute
  '/ologa': typeof OlogaRoute
  '/perfil': typeof PerfilRoute
  '/recuperar': typeof RecuperarRoute
  '/registo': typeof RegistoRoute
  '/verificar': typeof VerificarRoute
  '/api/public/admin-setup': typeof ApiPublicAdminSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/definir-palavra-passe': typeof DefinirPalavraPasseRoute
  '/entrar': typeof EntrarRoute
  '/formacao': typeof FormacaoRoute
  '/inscricao': typeof InscricaoRoute
  '/instituicao': typeof InstituicaoRoute
  '/ologa': typeof OlogaRoute
  '/perfil': typeof PerfilRoute
  '/recuperar': typeof RecuperarRoute
  '/registo': typeof RegistoRoute
  '/verificar': typeof VerificarRoute
  '/api/public/admin-setup': typeof ApiPublicAdminSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/definir-palavra-passe'
    | '/entrar'
    | '/formacao'
    | '/inscricao'
    | '/instituicao'
    | '/ologa'
    | '/perfil'
    | '/recuperar'
    | '/registo'
    | '/verificar'
    | '/api/public/admin-setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/definir-palavra-passe'
    | '/entrar'
    | '/formacao'
    | '/inscricao'
    | '/instituicao'
    | '/ologa'
    | '/perfil'
    | '/recuperar'
    | '/registo'
    | '/verificar'
    | '/api/public/admin-setup'
  id:
    | '__root__'
    | '/'
    | '/definir-palavra-passe'
    | '/entrar'
    | '/formacao'
    | '/inscricao'
    | '/instituicao'
    | '/ologa'
    | '/perfil'
    | '/recuperar'
    | '/registo'
    | '/verificar'
    | '/api/public/admin-setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DefinirPalavraPasseRoute: typeof DefinirPalavraPasseRoute
  EntrarRoute: typeof EntrarRoute
  FormacaoRoute: typeof FormacaoRoute
  InscricaoRoute: typeof InscricaoRoute
  InstituicaoRoute: typeof InstituicaoRoute
  OlogaRoute: typeof OlogaRoute
  PerfilRoute: typeof PerfilRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistoRoute: typeof RegistoRoute
  VerificarRoute: typeof VerificarRoute
  ApiPublicAdminSetupRoute: typeof ApiPublicAdminSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ologa': {
      id: '/ologa'
      path: '/ologa'
      fullPath: '/ologa'
      preLoaderRoute: typeof OlogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instituicao': {
      id: '/instituicao'
      path: '/instituicao'
      fullPath: '/instituicao'
      preLoaderRoute: typeof InstituicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formacao': {
      id: '/formacao'
      path: '/formacao'
      fullPath: '/formacao'
      preLoaderRoute: typeof FormacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-palavra-passe': {
      id: '/definir-palavra-passe'
      path: '/definir-palavra-passe'
      fullPath: '/definir-palavra-passe'
      preLoaderRoute: typeof DefinirPalavraPasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-setup': {
      id: '/api/public/admin-setup'
      path: '/api/public/admin-setup'
      fullPath: '/api/public/admin-setup'
      preLoaderRoute: typeof ApiPublicAdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DefinirPalavraPasseRoute: DefinirPalavraPasseRoute,
  EntrarRoute: EntrarRoute,
  FormacaoRoute: FormacaoRoute,
  InscricaoRoute: InscricaoRoute,
  InstituicaoRoute: InstituicaoRoute,
  OlogaRoute: OlogaRoute,
  PerfilRoute: PerfilRoute,
  RecuperarRoute: RecuperarRoute,
  RegistoRoute: RegistoRoute,
  VerificarRoute: VerificarRoute,
  ApiPublicAdminSetupRoute: ApiPublicAdminSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
