/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OlogaRouteImport } from './routes/ologa'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as FormacaoRouteImport } from './routes/formacao'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OlogaIndexRouteImport } from './routes/ologa.index'
import { Route as FormacaoIndexRouteImport } from './routes/formacao.index'
import { Route as OlogaNovaInstituicaoRouteImport } from './routes/ologa.nova-instituicao'
import { Route as FormacaoModuloRouteImport } from './routes/formacao.$modulo'
import { Route as FormacaoModuloIndexRouteImport } from './routes/formacao.$modulo.index'
import { Route as OlogaInstituicoesIdRouteImport } from './routes/ologa.instituicoes.$id'
import { Route as FormacaoModuloQuizRouteImport } from './routes/formacao.$modulo.quiz'
import { Route as FormacaoModuloLicaoLicaoRouteImport } from './routes/formacao.$modulo.licao.$licao'

const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OlogaRoute = OlogaRouteImport.update({
  id: '/ologa',
  path: '/ologa',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const FormacaoRoute = FormacaoRouteImport.update({
  id: '/formacao',
  path: '/formacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OlogaIndexRoute = OlogaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OlogaRoute,
} as any)
const FormacaoIndexRoute = FormacaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormacaoRoute,
} as any)
const OlogaNovaInstituicaoRoute = OlogaNovaInstituicaoRouteImport.update({
  id: '/nova-instituicao',
  path: '/nova-instituicao',
  getParentRoute: () => OlogaRoute,
} as any)
const FormacaoModuloRoute = FormacaoModuloRouteImport.update({
  id: '/$modulo',
  path: '/$modulo',
  getParentRoute: () => FormacaoRoute,
} as any)
const FormacaoModuloIndexRoute = FormacaoModuloIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormacaoModuloRoute,
} as any)
const OlogaInstituicoesIdRoute = OlogaInstituicoesIdRouteImport.update({
  id: '/instituicoes/$id',
  path: '/instituicoes/$id',
  getParentRoute: () => OlogaRoute,
} as any)
const FormacaoModuloQuizRoute = FormacaoModuloQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => FormacaoModuloRoute,
} as any)
const FormacaoModuloLicaoLicaoRoute =
  FormacaoModuloLicaoLicaoRouteImport.update({
    id: '/licao/$licao',
    path: '/licao/$licao',
    getParentRoute: () => FormacaoModuloRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/formacao': typeof FormacaoRouteWithChildren
  '/inscricao': typeof InscricaoRoute
  '/ologa': typeof OlogaRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/verificar': typeof VerificarRoute
  '/formacao/$modulo': typeof FormacaoModuloRouteWithChildren
  '/ologa/nova-instituicao': typeof OlogaNovaInstituicaoRoute
  '/formacao/': typeof FormacaoIndexRoute
  '/ologa/': typeof OlogaIndexRoute
  '/formacao/$modulo/quiz': typeof FormacaoModuloQuizRoute
  '/ologa/instituicoes/$id': typeof OlogaInstituicoesIdRoute
  '/formacao/$modulo/': typeof FormacaoModuloIndexRoute
  '/formacao/$modulo/licao/$licao': typeof FormacaoModuloLicaoLicaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/inscricao': typeof InscricaoRoute
  '/perfil': typeof PerfilRoute
  '/verificar': typeof VerificarRoute
  '/ologa/nova-instituicao': typeof OlogaNovaInstituicaoRoute
  '/formacao': typeof FormacaoIndexRoute
  '/ologa': typeof OlogaIndexRoute
  '/formacao/$modulo/quiz': typeof FormacaoModuloQuizRoute
  '/ologa/instituicoes/$id': typeof OlogaInstituicoesIdRoute
  '/formacao/$modulo': typeof FormacaoModuloIndexRoute
  '/formacao/$modulo/licao/$licao': typeof FormacaoModuloLicaoLicaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/formacao': typeof FormacaoRouteWithChildren
  '/inscricao': typeof InscricaoRoute
  '/ologa': typeof OlogaRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/verificar': typeof VerificarRoute
  '/formacao/$modulo': typeof FormacaoModuloRouteWithChildren
  '/ologa/nova-instituicao': typeof OlogaNovaInstituicaoRoute
  '/formacao/': typeof FormacaoIndexRoute
  '/ologa/': typeof OlogaIndexRoute
  '/formacao/$modulo/quiz': typeof FormacaoModuloQuizRoute
  '/ologa/instituicoes/$id': typeof OlogaInstituicoesIdRoute
  '/formacao/$modulo/': typeof FormacaoModuloIndexRoute
  '/formacao/$modulo/licao/$licao': typeof FormacaoModuloLicaoLicaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/formacao'
    | '/inscricao'
    | '/ologa'
    | '/perfil'
    | '/verificar'
    | '/formacao/$modulo'
    | '/ologa/nova-instituicao'
    | '/formacao/'
    | '/ologa/'
    | '/formacao/$modulo/quiz'
    | '/ologa/instituicoes/$id'
    | '/formacao/$modulo/'
    | '/formacao/$modulo/licao/$licao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/inscricao'
    | '/perfil'
    | '/verificar'
    | '/ologa/nova-instituicao'
    | '/formacao'
    | '/ologa'
    | '/formacao/$modulo/quiz'
    | '/ologa/instituicoes/$id'
    | '/formacao/$modulo'
    | '/formacao/$modulo/licao/$licao'
  id:
    | '__root__'
    | '/'
    | '/entrar'
    | '/formacao'
    | '/inscricao'
    | '/ologa'
    | '/perfil'
    | '/verificar'
    | '/formacao/$modulo'
    | '/ologa/nova-instituicao'
    | '/formacao/'
    | '/ologa/'
    | '/formacao/$modulo/quiz'
    | '/ologa/instituicoes/$id'
    | '/formacao/$modulo/'
    | '/formacao/$modulo/licao/$licao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntrarRoute: typeof EntrarRoute
  FormacaoRoute: typeof FormacaoRouteWithChildren
  InscricaoRoute: typeof InscricaoRoute
  OlogaRoute: typeof OlogaRouteWithChildren
  PerfilRoute: typeof PerfilRoute
  VerificarRoute: typeof VerificarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ologa': {
      id: '/ologa'
      path: '/ologa'
      fullPath: '/ologa'
      preLoaderRoute: typeof OlogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formacao': {
      id: '/formacao'
      path: '/formacao'
      fullPath: '/formacao'
      preLoaderRoute: typeof FormacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ologa/': {
      id: '/ologa/'
      path: '/'
      fullPath: '/ologa/'
      preLoaderRoute: typeof OlogaIndexRouteImport
      parentRoute: typeof OlogaRoute
    }
    '/formacao/': {
      id: '/formacao/'
      path: '/'
      fullPath: '/formacao/'
      preLoaderRoute: typeof FormacaoIndexRouteImport
      parentRoute: typeof FormacaoRoute
    }
    '/ologa/nova-instituicao': {
      id: '/ologa/nova-instituicao'
      path: '/nova-instituicao'
      fullPath: '/ologa/nova-instituicao'
      preLoaderRoute: typeof OlogaNovaInstituicaoRouteImport
      parentRoute: typeof OlogaRoute
    }
    '/formacao/$modulo': {
      id: '/formacao/$modulo'
      path: '/$modulo'
      fullPath: '/formacao/$modulo'
      preLoaderRoute: typeof FormacaoModuloRouteImport
      parentRoute: typeof FormacaoRoute
    }
    '/formacao/$modulo/': {
      id: '/formacao/$modulo/'
      path: '/'
      fullPath: '/formacao/$modulo/'
      preLoaderRoute: typeof FormacaoModuloIndexRouteImport
      parentRoute: typeof FormacaoModuloRoute
    }
    '/ologa/instituicoes/$id': {
      id: '/ologa/instituicoes/$id'
      path: '/instituicoes/$id'
      fullPath: '/ologa/instituicoes/$id'
      preLoaderRoute: typeof OlogaInstituicoesIdRouteImport
      parentRoute: typeof OlogaRoute
    }
    '/formacao/$modulo/quiz': {
      id: '/formacao/$modulo/quiz'
      path: '/quiz'
      fullPath: '/formacao/$modulo/quiz'
      preLoaderRoute: typeof FormacaoModuloQuizRouteImport
      parentRoute: typeof FormacaoModuloRoute
    }
    '/formacao/$modulo/licao/$licao': {
      id: '/formacao/$modulo/licao/$licao'
      path: '/licao/$licao'
      fullPath: '/formacao/$modulo/licao/$licao'
      preLoaderRoute: typeof FormacaoModuloLicaoLicaoRouteImport
      parentRoute: typeof FormacaoModuloRoute
    }
  }
}

interface FormacaoModuloRouteChildren {
  FormacaoModuloQuizRoute: typeof FormacaoModuloQuizRoute
  FormacaoModuloIndexRoute: typeof FormacaoModuloIndexRoute
  FormacaoModuloLicaoLicaoRoute: typeof FormacaoModuloLicaoLicaoRoute
}

const FormacaoModuloRouteChildren: FormacaoModuloRouteChildren = {
  FormacaoModuloQuizRoute: FormacaoModuloQuizRoute,
  FormacaoModuloIndexRoute: FormacaoModuloIndexRoute,
  FormacaoModuloLicaoLicaoRoute: FormacaoModuloLicaoLicaoRoute,
}

const FormacaoModuloRouteWithChildren = FormacaoModuloRoute._addFileChildren(
  FormacaoModuloRouteChildren,
)

interface FormacaoRouteChildren {
  FormacaoModuloRoute: typeof FormacaoModuloRouteWithChildren
  FormacaoIndexRoute: typeof FormacaoIndexRoute
}

const FormacaoRouteChildren: FormacaoRouteChildren = {
  FormacaoModuloRoute: FormacaoModuloRouteWithChildren,
  FormacaoIndexRoute: FormacaoIndexRoute,
}

const FormacaoRouteWithChildren = FormacaoRoute._addFileChildren(
  FormacaoRouteChildren,
)

interface OlogaRouteChildren {
  OlogaNovaInstituicaoRoute: typeof OlogaNovaInstituicaoRoute
  OlogaIndexRoute: typeof OlogaIndexRoute
  OlogaInstituicoesIdRoute: typeof OlogaInstituicoesIdRoute
}

const OlogaRouteChildren: OlogaRouteChildren = {
  OlogaNovaInstituicaoRoute: OlogaNovaInstituicaoRoute,
  OlogaIndexRoute: OlogaIndexRoute,
  OlogaInstituicoesIdRoute: OlogaInstituicoesIdRoute,
}

const OlogaRouteWithChildren = OlogaRoute._addFileChildren(OlogaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntrarRoute: EntrarRoute,
  FormacaoRoute: FormacaoRouteWithChildren,
  InscricaoRoute: InscricaoRoute,
  OlogaRoute: OlogaRouteWithChildren,
  PerfilRoute: PerfilRoute,
  VerificarRoute: VerificarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
